<div role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<?php echo $this->url(""); ?>" class="navbar-brand"><?php echo $this->getSiteTitle(); ?></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><?php echo $this->l("csv", $this->t("Get Countries CSV")); ?></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><?php echo $this->l("#", $this->t("Does Nothing")); ?></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>